//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistryCleanerCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistryCleanerCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Help Files.
        /// </summary>
        public static string ApplicationHelpFiles {
            get {
                return ResourceManager.GetString("ApplicationHelpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application History.
        /// </summary>
        public static string ApplicationHistory {
            get {
                return ResourceManager.GetString("ApplicationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID Paths.
        /// </summary>
        public static string ApplicationIDPaths {
            get {
                return ResourceManager.GetString("ApplicationIDPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path testing for invalid system help files....
        /// </summary>
        public static string CheckingApplicationHelpFiles {
            get {
                return ResourceManager.GetString("CheckingApplicationHelpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for invalid class id&apos;s....
        /// </summary>
        public static string CheckingClassNameRegistrations {
            get {
                return ResourceManager.GetString("CheckingClassNameRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path testing for invalid fonts....
        /// </summary>
        public static string CheckingFontPaths {
            get {
                return ResourceManager.GetString("CheckingFontPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing for invalid history links....
        /// </summary>
        public static string CheckingHistorySettings {
            get {
                return ResourceManager.GetString("CheckingHistorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path testing for valid shared library connections....
        /// </summary>
        public static string CheckingSharedLibraries {
            get {
                return ResourceManager.GetString("CheckingSharedLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing startup software entries....
        /// </summary>
        public static string CheckingStartupApplicationPaths {
            get {
                return ResourceManager.GetString("CheckingStartupApplicationPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path testing for user installed software....
        /// </summary>
        public static string CheckingUninstallExecutablePaths {
            get {
                return ResourceManager.GetString("CheckingUninstallExecutablePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing for VDM bug....
        /// </summary>
        public static string CheckingVirtualDeviceRegistration {
            get {
                return ResourceManager.GetString("CheckingVirtualDeviceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Key Edit Strings.
        /// </summary>
        public static string ClassKeyEditStrings {
            get {
                return ResourceManager.GetString("ClassKeyEditStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Key Open Strings.
        /// </summary>
        public static string ClassKeyOpenStrings {
            get {
                return ResourceManager.GetString("ClassKeyOpenStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Key Sub Paths.
        /// </summary>
        public static string ClassKeySubPaths {
            get {
                return ResourceManager.GetString("ClassKeySubPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name Registrations.
        /// </summary>
        public static string ClassNameRegistrations {
            get {
                return ResourceManager.GetString("ClassNameRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clsid Registrations.
        /// </summary>
        public static string ClsidRegistrations {
            get {
                return ResourceManager.GetString("ClsidRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing internal ID strings....
        /// </summary>
        public static string ComparingInternalID {
            get {
                return ResourceManager.GetString("ComparingInternalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Native Software Strings.
        /// </summary>
        public static string DeepNativeSoftwareStrings {
            get {
                return ResourceManager.GetString("DeepNativeSoftwareStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep software scan....
        /// </summary>
        public static string DeepSoftwareScan {
            get {
                return ResourceManager.GetString("DeepSoftwareScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep System Scan.
        /// </summary>
        public static string DeepSystemScan {
            get {
                return ResourceManager.GetString("DeepSystemScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep User Software Strings.
        /// </summary>
        public static string DeepUserSoftwareStrings {
            get {
                return ResourceManager.GetString("DeepUserSoftwareStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Paths.
        /// </summary>
        public static string FontPaths {
            get {
                return ResourceManager.GetString("FontPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help File Paths.
        /// </summary>
        public static string HelpFilePaths {
            get {
                return ResourceManager.GetString("HelpFilePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Files.
        /// </summary>
        public static string HelpFiles {
            get {
                return ResourceManager.GetString("HelpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History and Start Menu.
        /// </summary>
        public static string HistoryandStartMenu {
            get {
                return ResourceManager.GetString("HistoryandStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Explorer Strings.
        /// </summary>
        public static string HistoryExplorerStrings {
            get {
                return ResourceManager.GetString("HistoryExplorerStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link-Verlauf.
        /// </summary>
        public static string HistoryLinkStrings {
            get {
                return ResourceManager.GetString("HistoryLinkStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu-Verlauf.
        /// </summary>
        public static string HistoryMenuStrings {
            get {
                return ResourceManager.GetString("HistoryMenuStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Settings.
        /// </summary>
        public static string HistorySettings {
            get {
                return ResourceManager.GetString("HistorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Start Paths.
        /// </summary>
        public static string HistoryStartPaths {
            get {
                return ResourceManager.GetString("HistoryStartPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon-Pfade.
        /// </summary>
        public static string IconPaths {
            get {
                return ResourceManager.GetString("IconPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Strings.
        /// </summary>
        public static string InstallationStrings {
            get {
                return ResourceManager.GetString("InstallationStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Software.
        /// </summary>
        public static string InstalledSoftware {
            get {
                return ResourceManager.GetString("InstalledSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Proxy IDs.
        /// </summary>
        public static string InterfaceProxyIDs {
            get {
                return ResourceManager.GetString("InterfaceProxyIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Types.
        /// </summary>
        public static string InterfaceTypes {
            get {
                return ResourceManager.GetString("InterfaceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recently Used Lists.
        /// </summary>
        public static string MostRecentlyUsedLists {
            get {
                return ResourceManager.GetString("MostRecentlyUsedLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRU Lists.
        /// </summary>
        public static string MRULists {
            get {
                return ResourceManager.GetString("MRULists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRU Scan.
        /// </summary>
        public static string MRUScan {
            get {
                return ResourceManager.GetString("MRUScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcServer-Unterschlüssel.
        /// </summary>
        public static string ProcServerSubkeys {
            get {
                return ResourceManager.GetString("ProcServerSubkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Help Files.
        /// </summary>
        public static string RegisteredHelpFiles {
            get {
                return ResourceManager.GetString("RegisteredHelpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for MRU lists....
        /// </summary>
        public static string SearchingMRULists {
            get {
                return ResourceManager.GetString("SearchingMRULists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Libraries.
        /// </summary>
        public static string SharedLibraries {
            get {
                return ResourceManager.GetString("SharedLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Registrations.
        /// </summary>
        public static string SoftwareRegistrations {
            get {
                return ResourceManager.GetString("SoftwareRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Application Paths.
        /// </summary>
        public static string StartupApplicationPaths {
            get {
                return ResourceManager.GetString("StartupApplicationPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Entries.
        /// </summary>
        public static string StartupEntries {
            get {
                return ResourceManager.GetString("StartupEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Options.
        /// </summary>
        public static string StartupOptions {
            get {
                return ResourceManager.GetString("StartupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning: {0}.
        /// </summary>
        public static string StatusChangeFormat {
            get {
                return ResourceManager.GetString("StatusChangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Control Classes.
        /// </summary>
        public static string SystemControlClasses {
            get {
                return ResourceManager.GetString("SystemControlClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fonts.
        /// </summary>
        public static string SystemFonts {
            get {
                return ResourceManager.GetString("SystemFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Scan.
        /// </summary>
        public static string SystemScan {
            get {
                return ResourceManager.GetString("SystemScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Software.
        /// </summary>
        public static string SystemSoftware {
            get {
                return ResourceManager.GetString("SystemSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Class Interfaces....
        /// </summary>
        public static string TestingClassInterfaces {
            get {
                return ResourceManager.GetString("TestingClassInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Class key path references....
        /// </summary>
        public static string TestingClasskeyPathReferences {
            get {
                return ResourceManager.GetString("TestingClasskeyPathReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Type Library references....
        /// </summary>
        public static string TestingTypeLibraryReferences {
            get {
                return ResourceManager.GetString("TestingTypeLibraryReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing for invalid user software paths....
        /// </summary>
        public static string TestingUserSoftwarePaths {
            get {
                return ResourceManager.GetString("TestingUserSoftwarePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Libraries.
        /// </summary>
        public static string TypeLibraries {
            get {
                return ResourceManager.GetString("TypeLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Executable Paths.
        /// </summary>
        public static string UninstallExecutablePaths {
            get {
                return ResourceManager.GetString("UninstallExecutablePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Scan.
        /// </summary>
        public static string UserScan {
            get {
                return ResourceManager.GetString("UserScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Software.
        /// </summary>
        public static string UserSoftware {
            get {
                return ResourceManager.GetString("UserSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Software Paths.
        /// </summary>
        public static string UserSoftwarePaths {
            get {
                return ResourceManager.GetString("UserSoftwarePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Device Registration.
        /// </summary>
        public static string VirtualDeviceRegistration {
            get {
                return ResourceManager.GetString("VirtualDeviceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Devices.
        /// </summary>
        public static string VirtualDevices {
            get {
                return ResourceManager.GetString("VirtualDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 Help Files.
        /// </summary>
        public static string Win32HelpFiles {
            get {
                return ResourceManager.GetString("Win32HelpFiles", resourceCulture);
            }
        }
    }
}
