//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracksEraser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TracksEraser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tracks have been erased successfully !
        ///Please note that some files and registry keys are automatically regenerated by the operating system 
        ///once they are deleted, however the previous data in them has been reset..
        /// </summary>
        internal static string after_scan_msg {
            get {
                return ResourceManager.GetString("after_scan_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse.
        /// </summary>
        internal static string analyse {
            get {
                return ResourceManager.GetString("analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYSIS REPORT.
        /// </summary>
        internal static string analysis_report {
            get {
                return ResourceManager.GetString("analysis_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Forms - Auto Complete Passwords.
        /// </summary>
        internal static string auto_pass {
            get {
                return ResourceManager.GetString("auto_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        internal static string check_all {
            get {
                return ResourceManager.GetString("check_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check invert.
        /// </summary>
        internal static string check_invert {
            get {
                return ResourceManager.GetString("check_invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Internet Explorer cookies you want to delete and click &quot;Delete checked cookies now&quot; below..
        /// </summary>
        internal static string check_mark_cookies {
            get {
                return ResourceManager.GetString("check_mark_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Firefox cookies you want to delete and click &quot;Delete checked cookies now&quot; below..
        /// </summary>
        internal static string check_mark_cookies_ff {
            get {
                return ResourceManager.GetString("check_mark_cookies_ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Chrome cookies you want to delete and click &quot;Delete checked cookies now&quot; below..
        /// </summary>
        internal static string check_mark_cookies_google {
            get {
                return ResourceManager.GetString("check_mark_cookies_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Internet Explorer URLs you want to delete and click &quot;Delete checked URLs now&quot; below..
        /// </summary>
        internal static string check_mark_urls_ie {
            get {
                return ResourceManager.GetString("check_mark_urls_ie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check none.
        /// </summary>
        internal static string check_none {
            get {
                return ResourceManager.GetString("check_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome is already running, please close it then run scan again..
        /// </summary>
        internal static string close_chrome_to_erase {
            get {
                return ResourceManager.GetString("close_chrome_to_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close Firefox and retry.
        /// </summary>
        internal static string close_ff {
            get {
                return ResourceManager.GetString("close_ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox is already running, please close it then run scan again..
        /// </summary>
        internal static string close_firefox_to_erase {
            get {
                return ResourceManager.GetString("close_firefox_to_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close Chrome and retry.
        /// </summary>
        internal static string close_google {
            get {
                return ResourceManager.GetString("close_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires Internet Explorer to be closed. Are you sure Internet Explorer is closed?.
        /// </summary>
        internal static string close_ie_to_erase {
            get {
                return ResourceManager.GetString("close_ie_to_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer is already running, please close and try scanning again..
        /// </summary>
        internal static string close_ie_to_erase1 {
            get {
                return ResourceManager.GetString("close_ie_to_erase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires Internet Explorer to be closed. Are you sure Internet Explorer is closed?.
        /// </summary>
        internal static string close_iexplore_to_erase {
            get {
                return ResourceManager.GetString("close_iexplore_to_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires Firefox to be closed. Are you sure FireFox is closed?.
        /// </summary>
        internal static string closed_ff {
            get {
                return ResourceManager.GetString("closed_ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires Chrome to be closed. Are you sure Chrome is closed?.
        /// </summary>
        internal static string closed_google {
            get {
                return ResourceManager.GetString("closed_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This requires Internet Explorer to be closed. Are you sure Internet Explorer is closed?.
        /// </summary>
        internal static string CloseIE {
            get {
                return ResourceManager.GetString("CloseIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This requires Internet Explorer to be closed. Are you sure Internet Explorer is closed?.
        /// </summary>
        internal static string CloseIE1 {
            get {
                return ResourceManager.GetString("CloseIE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox is not installed.
        /// </summary>
        internal static string cookie_info_locked_ff {
            get {
                return ResourceManager.GetString("cookie_info_locked_ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome is not installed.
        /// </summary>
        internal static string cookie_info_locked_google {
            get {
                return ResourceManager.GetString("cookie_info_locked_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        internal static string cookies {
            get {
                return ResourceManager.GetString("cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete checked cookies now.
        /// </summary>
        internal static string del_cookies {
            get {
                return ResourceManager.GetString("del_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete checked URLs now.
        /// </summary>
        internal static string del_urls {
            get {
                return ResourceManager.GetString("del_urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of files to be deleted.
        /// </summary>
        internal static string details_files_tobe_del {
            get {
                return ResourceManager.GetString("details_files_tobe_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of Windows registry keys to be deleted.
        /// </summary>
        internal static string details_reg_tobe_del {
            get {
                return ResourceManager.GetString("details_reg_tobe_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase checked tracks.
        /// </summary>
        internal static string erase_check_track {
            get {
                return ResourceManager.GetString("erase_check_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like to erase using the checkbox to thte left of the track name.
        /// </summary>
        internal static string error_check_tracks {
            get {
                return ResourceManager.GetString("error_check_tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected tracks have been erased successfully.
        /// </summary>
        internal static string error_erased_succ {
            get {
                return ResourceManager.GetString("error_erased_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracks checked. To erase tracks, please check each track you would.
        /// </summary>
        internal static string error_no_tracks_checked {
            get {
                return ResourceManager.GetString("error_no_tracks_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing Recycle Bin.
        /// </summary>
        internal static string error_rec_bin {
            get {
                return ResourceManager.GetString("error_rec_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any items to analyze.
        /// </summary>
        internal static string error_select {
            get {
                return ResourceManager.GetString("error_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to erase.
        /// </summary>
        internal static string error_sure {
            get {
                return ResourceManager.GetString("error_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track(s).
        /// </summary>
        internal static string error_tracks {
            get {
                return ResourceManager.GetString("error_tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF Cookie Manager.
        /// </summary>
        internal static string ff_cookie_manager {
            get {
                return ResourceManager.GetString("ff_cookie_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Common Dialog - File/Folder List.
        /// </summary>
        internal static string file_folder_list {
            get {
                return ResourceManager.GetString("file_folder_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) and.
        /// </summary>
        internal static string files_and {
            get {
                return ResourceManager.GetString("files_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) from.
        /// </summary>
        internal static string files_from {
            get {
                return ResourceManager.GetString("files_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox.
        /// </summary>
        internal static string firefox {
            get {
                return ResourceManager.GetString("firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox - Internet Cache.
        /// </summary>
        internal static string firefox_cache {
            get {
                return ResourceManager.GetString("firefox_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox - Cookies.
        /// </summary>
        internal static string firefox_cookies {
            get {
                return ResourceManager.GetString("firefox_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox - Download Manager History.
        /// </summary>
        internal static string firefox_download_history {
            get {
                return ResourceManager.GetString("firefox_download_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox - History.
        /// </summary>
        internal static string firefox_history {
            get {
                return ResourceManager.GetString("firefox_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox - Saved Form Information.
        /// </summary>
        internal static string firefox_saved_info {
            get {
                return ResourceManager.GetString("firefox_saved_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox - Saved Passwords.
        /// </summary>
        internal static string firefox_saved_pass {
            get {
                return ResourceManager.GetString("firefox_saved_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox - Search History.
        /// </summary>
        internal static string firefox_search_history {
            get {
                return ResourceManager.GetString("firefox_search_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome.
        /// </summary>
        internal static string google {
            get {
                return ResourceManager.GetString("google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome - Internet Cache.
        /// </summary>
        internal static string google_cache {
            get {
                return ResourceManager.GetString("google_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome is running. Please close the Google Chrome browser to delete cookies..
        /// </summary>
        internal static string google_chrome_running {
            get {
                return ResourceManager.GetString("google_chrome_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome Cookie Manager.
        /// </summary>
        internal static string google_cookie_manager {
            get {
                return ResourceManager.GetString("google_cookie_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome - Cookies.
        /// </summary>
        internal static string google_cookies {
            get {
                return ResourceManager.GetString("google_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome - Download History.
        /// </summary>
        internal static string google_download_history {
            get {
                return ResourceManager.GetString("google_download_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome - History.
        /// </summary>
        internal static string google_history {
            get {
                return ResourceManager.GetString("google_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome - Saved From Information.
        /// </summary>
        internal static string google_saved_info {
            get {
                return ResourceManager.GetString("google_saved_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/company/faq/.
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer.
        /// </summary>
        internal static string ie {
            get {
                return ResourceManager.GetString("ie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE Cookie Manager.
        /// </summary>
        internal static string ie_cookie_mngr {
            get {
                return ResourceManager.GetString("ie_cookie_mngr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer Cookies.
        /// </summary>
        internal static string ie_cookies {
            get {
                return ResourceManager.GetString("ie_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer History.
        /// </summary>
        internal static string ie_history {
            get {
                return ResourceManager.GetString("ie_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE History item:.
        /// </summary>
        internal static string ie_history_item {
            get {
                return ResourceManager.GetString("ie_history_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer is running. Please close the Internet Explorer browser to delete cookies..
        /// </summary>
        internal static string ie_running {
            get {
                return ResourceManager.GetString("ie_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE Typed URLs.
        /// </summary>
        internal static string ie_typed_urls {
            get {
                return ResourceManager.GetString("ie_typed_urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer - URL History.
        /// </summary>
        internal static string ie_url_history {
            get {
                return ResourceManager.GetString("ie_url_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.dat Files.
        /// </summary>
        internal static string index_files {
            get {
                return ResourceManager.GetString("index_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item cant be checked, because it&apos;s already running or not installed..
        /// </summary>
        internal static string item_running_or_installed {
            get {
                return ResourceManager.GetString("item_running_or_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macromedia Flash Player.
        /// </summary>
        internal static string mmfp {
            get {
                return ResourceManager.GetString("mmfp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox is running. Please close the Mozilla Firefox browser to delete cookies..
        /// </summary>
        internal static string mozilla_firefox_running {
            get {
                return ResourceManager.GetString("mozilla_firefox_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Player.
        /// </summary>
        internal static string mp {
            get {
                return ResourceManager.GetString("mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Management Console.
        /// </summary>
        internal static string ms_management_console {
            get {
                return ResourceManager.GetString("ms_management_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Paint.
        /// </summary>
        internal static string ms_paint {
            get {
                return ResourceManager.GetString("ms_paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Wordpad.
        /// </summary>
        internal static string ms_wordpad {
            get {
                return ResourceManager.GetString("ms_wordpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Network Places.
        /// </summary>
        internal static string network_places {
            get {
                return ResourceManager.GetString("network_places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office.
        /// </summary>
        internal static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-ins.
        /// </summary>
        internal static string plugins {
            get {
                return ResourceManager.GetString("plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickTime Player.
        /// </summary>
        internal static string qp {
            get {
                return ResourceManager.GetString("qp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry entries from.
        /// </summary>
        internal static string registries_from {
            get {
                return ResourceManager.GetString("registries_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run eraser.
        /// </summary>
        internal static string run_eraser {
            get {
                return ResourceManager.GetString("run_eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan started..
        /// </summary>
        internal static string scan_started {
            get {
                return ResourceManager.GetString("scan_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string scanning {
            get {
                return ResourceManager.GetString("scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of selected tracks.
        /// </summary>
        internal static string scanning_tracks {
            get {
                return ResourceManager.GetString("scanning_tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only available eraseable tracks.
        /// </summary>
        internal static string show_av_er_tracks {
            get {
                return ResourceManager.GetString("show_av_er_tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu Click History.
        /// </summary>
        internal static string start_menu_history {
            get {
                return ResourceManager.GetString("start_menu_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusStrip1.
        /// </summary>
        internal static string status_strip {
            get {
                return ResourceManager.GetString("status_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Java.
        /// </summary>
        internal static string sun_java {
            get {
                return ResourceManager.GetString("sun_java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error.
        /// </summary>
        internal static string sys_error {
            get {
                return ResourceManager.GetString("sys_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Internet Files.
        /// </summary>
        internal static string temp_internet_files {
            get {
                return ResourceManager.GetString("temp_internet_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be removed.
        /// </summary>
        internal static string tobe_removed {
            get {
                return ResourceManager.GetString("tobe_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items to be removed in Windows registry.
        /// </summary>
        internal static string tobe_removed_win_reg {
            get {
                return ResourceManager.GetString("tobe_removed_win_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStrip1.
        /// </summary>
        internal static string toolStrip {
            get {
                return ResourceManager.GetString("toolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase tracks.
        /// </summary>
        internal static string track_eraser {
            get {
                return ResourceManager.GetString("track_eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string tracks {
            get {
                return ResourceManager.GetString("tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase tracks.
        /// </summary>
        internal static string tracks_eraser {
            get {
                return ResourceManager.GetString("tracks_eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLs.
        /// </summary>
        internal static string urls {
            get {
                return ResourceManager.GetString("urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Clipboard.
        /// </summary>
        internal static string win_clipboard {
            get {
                return ResourceManager.GetString("win_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Defender.
        /// </summary>
        internal static string win_def {
            get {
                return ResourceManager.GetString("win_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Mapped Network Drives.
        /// </summary>
        internal static string win_map_drives {
            get {
                return ResourceManager.GetString("win_map_drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Recycle Bin.
        /// </summary>
        internal static string win_rec_bin {
            get {
                return ResourceManager.GetString("win_rec_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Recent Documents.
        /// </summary>
        internal static string win_rec_doc {
            get {
                return ResourceManager.GetString("win_rec_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Start Menu Run.
        /// </summary>
        internal static string win_st_menu_run {
            get {
                return ResourceManager.GetString("win_st_menu_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Temporary Files.
        /// </summary>
        internal static string win_temp_files {
            get {
                return ResourceManager.GetString("win_temp_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winrar.
        /// </summary>
        internal static string winrar {
            get {
                return ResourceManager.GetString("winrar", resourceCulture);
            }
        }
    }
}
