"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "1Click.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "BrowserAssistant.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "BugReporter.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Context Menu Manager.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Decrypter.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Disk Cleaner.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "DiskAnalysis.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "EmptyFolderFinder.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "EncryptDecrypt.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "File Splitter and Joiner.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "FileShredder.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "FileUndelete.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "freemiumContext.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "FreemiumUtilites.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Joiner.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "memopti.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Memory Optimizer.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "ProcessManager.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Registry Compactor.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "RegistryCleaner.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "shortcut.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Startup Manager.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "SystemInformation.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "TracksEraser.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "Uninstall_Manager.saproj"
"C:\Program Files\Red Gate\SmartAssembly 6\SmartAssembly.com" /build "WindowsStandardTools.saproj"
timeout 10