//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistryCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistryCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need administrative rights to use this functionality..
        /// </summary>
        public static string AdminRightsNeeded {
            get {
                return ResourceManager.GetString("AdminRightsNeeded", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted deletion of value:.
        /// </summary>
        public static string AttemptedDeletionOfValue {
            get {
                return ResourceManager.GetString("AttemptedDeletionOfValue", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap bottomBar {
            get {
                object obj = ResourceManager.GetObject("bottomBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel scan.
        /// </summary>
        public static string CancelScan {
            get {
                return ResourceManager.GetString("CancelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Scan.
        /// </summary>
        public static string ControlScanTitle {
            get {
                return ResourceManager.GetString("ControlScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep System Scan.
        /// </summary>
        public static string DeepScanTitle {
            get {
                return ResourceManager.GetString("DeepScanTitle", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap desktop_icon {
            get {
                object obj = ResourceManager.GetObject("desktop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fonts.
        /// </summary>
        public static string FontScanTitle {
            get {
                return ResourceManager.GetString("FontScanTitle", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap help_off {
            get {
                object obj = ResourceManager.GetObject("help_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap help_on {
            get {
                object obj = ResourceManager.GetObject("help_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help files.
        /// </summary>
        public static string HelpScanTitle {
            get {
                return ResourceManager.GetString("HelpScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/company/faq/.
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History and Start Menu.
        /// </summary>
        public static string HistoryScanTitle {
            get {
                return ResourceManager.GetString("HistoryScanTitle", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap icon_registry_Cleaner {
            get {
                object obj = ResourceManager.GetObject("icon_registry_Cleaner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection.
        /// </summary>
        public static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items cleared.
        /// </summary>
        public static string ItemsCleared {
            get {
                return ResourceManager.GetString("ItemsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last registry clean was on {0:hh:mm dd-MM-yy}.
        /// </summary>
        public static string LastCleanTime {
            get {
                return ResourceManager.GetString("LastCleanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Libraries.
        /// </summary>
        public static string LibraryScanTitle {
            get {
                return ResourceManager.GetString("LibraryScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRU Lists.
        /// </summary>
        public static string MRUScanTitle {
            get {
                return ResourceManager.GetString("MRUScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Selected.
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check registry categories and press Scan now.
        /// </summary>
        public static string NotStartedHeader {
            get {
                return ResourceManager.GetString("NotStartedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string NowScanning {
            get {
                return ResourceManager.GetString("NowScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problems were found. A rescan is recommended to find more problems..
        /// </summary>
        public static string ProblemsFound {
            get {
                return ResourceManager.GetString("ProblemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problems were found. Select the ones you want to remove and press Start cleaning..
        /// </summary>
        public static string ProblemsFoundClickClear {
            get {
                return ResourceManager.GetString("ProblemsFoundClickClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean registry.
        /// </summary>
        public static string RegistryCleaner {
            get {
                return ResourceManager.GetString("RegistryCleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry has been cleaned..
        /// </summary>
        public static string RegistryCleaningCompleted {
            get {
                return ResourceManager.GetString("RegistryCleaningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry scan canceled..
        /// </summary>
        public static string RegistryScanCanceled {
            get {
                return ResourceManager.GetString("RegistryScanCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry scan completed..
        /// </summary>
        public static string RegistryScanCompleted {
            get {
                return ResourceManager.GetString("RegistryScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items were removed successfully..
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring is disabled..
        /// </summary>
        public static string RestoreDisabled {
            get {
                return ResourceManager.GetString("RestoreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some modules first..
        /// </summary>
        public static string ScanAborted {
            get {
                return ResourceManager.GetString("ScanAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan was aborted by user..
        /// </summary>
        public static string ScanAbortedByUser {
            get {
                return ResourceManager.GetString("ScanAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again.
        /// </summary>
        public static string ScanAgain {
            get {
                return ResourceManager.GetString("ScanAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning:.
        /// </summary>
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Registry.
        /// </summary>
        public static string ScanningRegistry {
            get {
                return ResourceManager.GetString("ScanningRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan now.
        /// </summary>
        public static string ScanNow {
            get {
                return ResourceManager.GetString("ScanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Results were Reset..
        /// </summary>
        public static string ScanResultsReset {
            get {
                return ResourceManager.GetString("ScanResultsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Started....
        /// </summary>
        public static string ScanStarted {
            get {
                return ResourceManager.GetString("ScanStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not select any categories. Please check at least one..
        /// </summary>
        public static string SelectAtLeastOneItem {
            get {
                return ResourceManager.GetString("SelectAtLeastOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select something first before start cleaning..
        /// </summary>
        public static string SelectItemsToRemove {
            get {
                return ResourceManager.GetString("SelectItemsToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to set up a system restore point before proceeding? Without, changes to your system can not be undone..
        /// </summary>
        public static string SetUpSystemRestore {
            get {
                return ResourceManager.GetString("SetUpSystemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Software.
        /// </summary>
        public static string SoftwareScanTitle {
            get {
                return ResourceManager.GetString("SoftwareScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cleaning.
        /// </summary>
        public static string StartClearing {
            get {
                return ResourceManager.GetString("StartClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Entries.
        /// </summary>
        public static string StartupScanTitle {
            get {
                return ResourceManager.GetString("StartupScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful..
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore.
        /// </summary>
        public static string SystemRestore {
            get {
                return ResourceManager.GetString("SystemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore is unavailable or deactivated. Option was disabled..
        /// </summary>
        public static string SystemRestoreDeactivated {
            get {
                return ResourceManager.GetString("SystemRestoreDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore is either disabled or unavailable on this computer..
        /// </summary>
        public static string SystemRestoreUnavailable {
            get {
                return ResourceManager.GetString("SystemRestoreUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore is turned off, Would you like to continue at your own risk?.
        /// </summary>
        public static string SystemRestoreUnavailableRunFixAnyway {
            get {
                return ResourceManager.GetString("SystemRestoreUnavailableRunFixAnyway", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap thinBar {
            get {
                object obj = ResourceManager.GetObject("thinBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Strings.
        /// </summary>
        public static string UninstallScanTitle {
            get {
                return ResourceManager.GetString("UninstallScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Scan.
        /// </summary>
        public static string UserScanTitle {
            get {
                return ResourceManager.GetString("UserScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Devices.
        /// </summary>
        public static string VdmScanTitle {
            get {
                return ResourceManager.GetString("VdmScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to create a system restore point before proceeding? This process may take several minutes to complete..
        /// </summary>
        public static string WouldYouLikeToCreateRestorePoint {
            get {
                return ResourceManager.GetString("WouldYouLikeToCreateRestorePoint", resourceCulture);
            }
        }
    }
}
