//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistryCompactor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistryCompactor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another program seems to be already running....
        /// </summary>
        public static string AlreadyRunningError {
            get {
                return ResourceManager.GetString("AlreadyRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse.
        /// </summary>
        public static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse Registry.
        /// </summary>
        public static string AnalyseRegistry {
            get {
                return ResourceManager.GetString("AnalyseRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must analyze the hive before you can optimize it.
        /// </summary>
        public static string AnalyzeBeforeCompactError {
            get {
                return ResourceManager.GetString("AnalyzeBeforeCompactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze the Registry.
        /// </summary>
        public static string AnalyzeRegistry {
            get {
                return ResourceManager.GetString("AnalyzeRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing.
        /// </summary>
        public static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Registry.
        /// </summary>
        public static string AnalyzingRegistry {
            get {
                return ResourceManager.GetString("AnalyzingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Results.
        /// </summary>
        public static string AnalyzingResults {
            get {
                return ResourceManager.GetString("AnalyzingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottomBar {
            get {
                object obj = ResourceManager.GetObject("bottomBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must close running programs before optimizing the registry. Please save your work and close any running programs now..
        /// </summary>
        public static string CloseProgramsBeforeOptimizing {
            get {
                return ResourceManager.GetString("CloseProgramsBeforeOptimizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize.
        /// </summary>
        public static string Compact {
            get {
                return ResourceManager.GetString("Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing.
        /// </summary>
        public static string Compacting {
            get {
                return ResourceManager.GetString("Compacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing Registry.
        /// </summary>
        public static string CompactingRegistry {
            get {
                return ResourceManager.GetString("CompactingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create system restore points automatically.
        /// </summary>
        public static string CreateSystemRestorePointsAutomatically {
            get {
                return ResourceManager.GetString("CreateSystemRestorePointsAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize the registry.
        /// </summary>
        public static string DefragmentRegistry {
            get {
                return ResourceManager.GetString("DefragmentRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize the registry.
        /// </summary>
        public static string DefragRegistry {
            get {
                return ResourceManager.GetString("DefragRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap desktop_icon {
            get {
                object obj = ResourceManager.GetObject("desktop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display system information.
        /// </summary>
        public static string DisplaySystemInformation {
            get {
                return ResourceManager.GetString("DisplaySystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elasped Time:.
        /// </summary>
        public static string ElaspedTime {
            get {
                return ResourceManager.GetString("ElaspedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon FSUIcon {
            get {
                object obj = ResourceManager.GetObject("FSUIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help_off {
            get {
                object obj = ResourceManager.GetObject("help_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help_on {
            get {
                object obj = ResourceManager.GetObject("help_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/company/faq/.
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open hive list... this can be a problem!.
        /// </summary>
        public static string HiveListError {
            get {
                return ResourceManager.GetString("HiveListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hives.
        /// </summary>
        public static string Hives {
            get {
                return ResourceManager.GetString("Hives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_registry_compactor {
            get {
                object obj = ResourceManager.GetObject("icon_registry_compactor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Optimization.
        /// </summary>
        public static string LastOptimization {
            get {
                return ResourceManager.GetString("LastOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Optimization Performed:.
        /// </summary>
        public static string LastOptimizationPerformed {
            get {
                return ResourceManager.GetString("LastOptimizationPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingTripleColon {
            get {
                return ResourceManager.GetString("LoadingTripleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory:.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Scans Performed:.
        /// </summary>
        public static string NumberOfScansPerformed {
            get {
                return ResourceManager.GetString("NumberOfScansPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System:.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PCCleanerIcon {
            get {
                object obj = ResourceManager.GetObject("PCCleanerIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later....
        /// </summary>
        public static string PleaseTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor:.
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Stats.
        /// </summary>
        public static string ProgramStats {
            get {
                return ResourceManager.GetString("ProgramStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry hive.
        /// </summary>
        public static string RegHive {
            get {
                return ResourceManager.GetString("RegHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that the registry has already been optimized..
        /// </summary>
        public static string RegistryAlreadyCompacted {
            get {
                return ResourceManager.GetString("RegistryAlreadyCompacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize Registry.
        /// </summary>
        public static string RegistryCompactor {
            get {
                return ResourceManager.GetString("RegistryCompactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module defrags, optimizes and compacts the windows registry by removing unnecessary gaps and wasted space. This can improve the system performance and boost registry access..
        /// </summary>
        public static string RegistryCompactorDesc {
            get {
                return ResourceManager.GetString("RegistryCompactorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize registry - Options.
        /// </summary>
        public static string RegistryCompactorOptions {
            get {
                return ResourceManager.GetString("RegistryCompactorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can take several minutes. Are you sure you want to optimize your registry?.
        /// </summary>
        public static string RegistryCompactQuestion {
            get {
                return ResourceManager.GetString("RegistryCompactQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows Registry does NOT need to be optimized.
        /// </summary>
        public static string RegistryDoesntNeedCompact {
            get {
                return ResourceManager.GetString("RegistryDoesntNeedCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Files.
        /// </summary>
        public static string RegistryFiles {
            get {
                return ResourceManager.GetString("RegistryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the registry hives.
        /// </summary>
        public static string RegistryHiveLoadError {
            get {
                return ResourceManager.GetString("RegistryHiveLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows Registry needs to be optimized.
        /// </summary>
        public static string RegistryNeedsCompact {
            get {
                return ResourceManager.GetString("RegistryNeedsCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Size.
        /// </summary>
        public static string RegistrySize {
            get {
                return ResourceManager.GetString("RegistrySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Size:.
        /// </summary>
        public static string RegistrySizeColon {
            get {
                return ResourceManager.GetString("RegistrySizeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hive has already been analyzed.
        /// </summary>
        public static string RegistryValueAlreadyAnalyzedError {
            get {
                return ResourceManager.GetString("RegistryValueAlreadyAnalyzedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hive has already been optimized.
        /// </summary>
        public static string RegistryValueAlreadyCompactedError {
            get {
                return ResourceManager.GetString("RegistryValueAlreadyCompactedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart your computer before the new setting will take effect. Do you want to restart your computer now?.
        /// </summary>
        public static string RestartComputerQuestion {
            get {
                return ResourceManager.GetString("RestartComputerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Analysis Results.
        /// </summary>
        public static string ReviewAnalysisResults {
            get {
                return ResourceManager.GetString("ReviewAnalysisResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Performed.
        /// </summary>
        public static string ScansPerformed {
            get {
                return ResourceManager.GetString("ScansPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Saved:.
        /// </summary>
        public static string SpaceSaved {
            get {
                return ResourceManager.GetString("SpaceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start optimization.
        /// </summary>
        public static string StartRegistryDefrag {
            get {
                return ResourceManager.GetString("StartRegistryDefrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The level of registry fragmentation will be checked.
        /// </summary>
        public static string Step1Desc {
            get {
                return ResourceManager.GetString("Step1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A report will be generated with the analysis results and a recommendation.
        /// </summary>
        public static string Step2Desc {
            get {
                return ResourceManager.GetString("Step2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry will be optimized. A restart is required at the end.
        /// </summary>
        public static string Step3Desc {
            get {
                return ResourceManager.GetString("Step3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Steps to complete the process:.
        /// </summary>
        public static string StepsToComplete {
            get {
                return ResourceManager.GetString("StepsToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        public static string StepXofY {
            get {
                return ResourceManager.GetString("StepXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap thinBar {
            get {
                object obj = ResourceManager.GetObject("thinBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Elasped Time:.
        /// </summary>
        public static string TotalElapsedTime {
            get {
                return ResourceManager.GetString("TotalElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total memory.
        /// </summary>
        public static string TotalMemory {
            get {
                return ResourceManager.GetString("TotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Space Saved:.
        /// </summary>
        public static string TotalSpaceSaved {
            get {
                return ResourceManager.GetString("TotalSpaceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updater encountered an error.
        /// </summary>
        public static string UpdaterError {
            get {
                return ResourceManager.GetString("UpdaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View System Info.
        /// </summary>
        public static string ViewSystemInfo {
            get {
                return ResourceManager.GetString("ViewSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Information.
        /// </summary>
        public static string WindowsRegistryInformation {
            get {
                return ResourceManager.GetString("WindowsRegistryInformation", resourceCulture);
            }
        }
    }
}
