//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uninstall_Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uninstall_Manager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch uninstall.
        /// </summary>
        internal static string batch_uninstall {
            get {
                return ResourceManager.GetString("batch_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line.
        /// </summary>
        internal static string command_line {
            get {
                return ResourceManager.GetString("command_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently installed programs.
        /// </summary>
        internal static string current_installed_progs {
            get {
                return ResourceManager.GetString("current_installed_progs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries have been removed successfully.
        /// </summary>
        internal static string entries_removed {
            get {
                return ResourceManager.GetString("entries_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that removing an entry is an irreversible process, it&apos;s better to try uninstalling first. Are you sure you want to remove selected item(s) ?.
        /// </summary>
        internal static string entry_remove_confirm {
            get {
                return ResourceManager.GetString("entry_remove_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        internal static string error_occurred {
            get {
                return ResourceManager.GetString("error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been imported.
        /// </summary>
        internal static string file_imported {
            get {
                return ResourceManager.GetString("file_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FSUIcon {
            get {
                object obj = ResourceManager.GetObject("FSUIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/company/faq/.
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed date.
        /// </summary>
        internal static string installed_date {
            get {
                return ResourceManager.GetString("installed_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string installed_on {
            get {
                return ResourceManager.GetString("installed_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is update.
        /// </summary>
        internal static string is_update {
            get {
                return ResourceManager.GetString("is_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need administrative rights to use this functionality..
        /// </summary>
        internal static string no_one_removed {
            get {
                return ResourceManager.GetString("no_one_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry has been removed successfully.
        /// </summary>
        internal static string one_entry_removed {
            get {
                return ResourceManager.GetString("one_entry_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        internal static string operation_cancelled {
            get {
                return ResourceManager.GetString("operation_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PCCleanerIcon {
            get {
                object obj = ResourceManager.GetObject("PCCleanerIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string programs {
            get {
                return ResourceManager.GetString("programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs installed on your computer (Total.
        /// </summary>
        internal static string programs_installed_total {
            get {
                return ResourceManager.GetString("programs_installed_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string publisher {
            get {
                return ResourceManager.GetString("publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regKey.
        /// </summary>
        internal static string reg_key {
            get {
                return ResourceManager.GetString("reg_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove entries.
        /// </summary>
        internal static string remove_entries {
            get {
                return ResourceManager.GetString("remove_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove entry.
        /// </summary>
        internal static string remove_entry {
            get {
                return ResourceManager.GetString("remove_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report created on.
        /// </summary>
        internal static string report_created_on {
            get {
                return ResourceManager.GetString("report_created_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been saved to.
        /// </summary>
        internal static string saved_to {
            get {
                return ResourceManager.GetString("saved_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search program.
        /// </summary>
        internal static string search_program {
            get {
                return ResourceManager.GetString("search_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows Updates.
        /// </summary>
        internal static string show_win_updates {
            get {
                return ResourceManager.GetString("show_win_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall programs.
        /// </summary>
        internal static string uninstall_manager {
            get {
                return ResourceManager.GetString("uninstall_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall this program.
        /// </summary>
        internal static string uninstall_program {
            get {
                return ResourceManager.GetString("uninstall_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall programs.
        /// </summary>
        internal static string uninstall_programs {
            get {
                return ResourceManager.GetString("uninstall_programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall files could not be found for {0}, Do you want to remove it from the list?.
        /// </summary>
        internal static string unistaller_not_found {
            get {
                return ResourceManager.GetString("unistaller_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
