//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreemiumUtilities.RegCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreemiumUtilities.RegCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attempted deletion of value: ähnelt.
        /// </summary>
        public static string AttemptedDeletionOfValue {
            get {
                return ResourceManager.GetString("AttemptedDeletionOfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Scan ähnelt.
        /// </summary>
        public static string CancelScan {
            get {
                return ResourceManager.GetString("CancelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control Scan ähnelt.
        /// </summary>
        public static string ControlScanTitle {
            get {
                return ResourceManager.GetString("ControlScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep System Scan ähnelt.
        /// </summary>
        public static string DeepScanTitle {
            get {
                return ResourceManager.GetString("DeepScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap desktop_icon {
            get {
                object obj = ResourceManager.GetObject("desktop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die failed. ähnelt.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Fonts ähnelt.
        /// </summary>
        public static string FontScanTitle {
            get {
                return ResourceManager.GetString("FontScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame0 {
            get {
                object obj = ResourceManager.GetObject("frame0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame1 {
            get {
                object obj = ResourceManager.GetObject("frame1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame2 {
            get {
                object obj = ResourceManager.GetObject("frame2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame3 {
            get {
                object obj = ResourceManager.GetObject("frame3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame4 {
            get {
                object obj = ResourceManager.GetObject("frame4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame5 {
            get {
                object obj = ResourceManager.GetObject("frame5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame6 {
            get {
                object obj = ResourceManager.GetObject("frame6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame7 {
            get {
                object obj = ResourceManager.GetObject("frame7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Help Files ähnelt.
        /// </summary>
        public static string HelpScanTitle {
            get {
                return ResourceManager.GetString("HelpScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History and Start Menu ähnelt.
        /// </summary>
        public static string HistoryScanTitle {
            get {
                return ResourceManager.GetString("HistoryScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Selection! ähnelt.
        /// </summary>
        public static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die items cleared ähnelt.
        /// </summary>
        public static string ItemsCleared {
            get {
                return ResourceManager.GetString("ItemsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last time you cleaned registry was {0:hh:mm dd-MM-yy} ähnelt.
        /// </summary>
        public static string LastCleanTime {
            get {
                return ResourceManager.GetString("LastCleanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared Libraries ähnelt.
        /// </summary>
        public static string LibraryScanTitle {
            get {
                return ResourceManager.GetString("LibraryScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MRU Lists ähnelt.
        /// </summary>
        public static string MRUScanTitle {
            get {
                return ResourceManager.GetString("MRUScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Items Selected ähnelt.
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check registry categories and press scan ähnelt.
        /// </summary>
        public static string NotStartedHeader {
            get {
                return ResourceManager.GetString("NotStartedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing ähnelt.
        /// </summary>
        public static string NowScanning {
            get {
                return ResourceManager.GetString("NowScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die problems were found. To scan again is recommended to find more problems. ähnelt.
        /// </summary>
        public static string ProblemsFound {
            get {
                return ResourceManager.GetString("ProblemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die problems were found. Select ones you want to remove and press Start Clearing. ähnelt.
        /// </summary>
        public static string ProblemsFoundClickClear {
            get {
                return ResourceManager.GetString("ProblemsFoundClickClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry Cleaner ähnelt.
        /// </summary>
        public static string RegistryCleaner {
            get {
                return ResourceManager.GetString("RegistryCleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry Cleaning Completed ähnelt.
        /// </summary>
        public static string RegistryCleaningCompleted {
            get {
                return ResourceManager.GetString("RegistryCleaningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry Scan Canceled ähnelt.
        /// </summary>
        public static string RegistryScanCanceled {
            get {
                return ResourceManager.GetString("RegistryScanCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry Scan Completed ähnelt.
        /// </summary>
        public static string RegistryScanCompleted {
            get {
                return ResourceManager.GetString("RegistryScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items removal action completed successfully. ähnelt.
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore Disabled! ähnelt.
        /// </summary>
        public static string RestoreDisabled {
            get {
                return ResourceManager.GetString("RestoreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Aborted, No Segments selected. ähnelt.
        /// </summary>
        public static string ScanAborted {
            get {
                return ResourceManager.GetString("ScanAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Aborted by User. ähnelt.
        /// </summary>
        public static string ScanAbortedByUser {
            get {
                return ResourceManager.GetString("ScanAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Again ähnelt.
        /// </summary>
        public static string ScanAgain {
            get {
                return ResourceManager.GetString("ScanAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning: ähnelt.
        /// </summary>
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning Registry ähnelt.
        /// </summary>
        public static string ScanningRegistry {
            get {
                return ResourceManager.GetString("ScanningRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Now ähnelt.
        /// </summary>
        public static string ScanNow {
            get {
                return ResourceManager.GetString("ScanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Results were Reset. ähnelt.
        /// </summary>
        public static string ScanResultsReset {
            get {
                return ResourceManager.GetString("ScanResultsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Started... ähnelt.
        /// </summary>
        public static string ScanStarted {
            get {
                return ResourceManager.GetString("ScanStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You do not have any scan segments selected, please check at least one ähnelt.
        /// </summary>
        public static string SelectAtLeastOneItem {
            get {
                return ResourceManager.GetString("SelectAtLeastOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You haven&apos;t selected any items for removal. To Reset the Scan Results, select Cancel ähnelt.
        /// </summary>
        public static string SelectItemsToRemove {
            get {
                return ResourceManager.GetString("SelectItemsToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to set up System Restore before proceeding? Without System Restore, changes to your system can Not be Undone ähnelt.
        /// </summary>
        public static string SetUpSystemRestore {
            get {
                return ResourceManager.GetString("SetUpSystemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Software ähnelt.
        /// </summary>
        public static string SoftwareScanTitle {
            get {
                return ResourceManager.GetString("SoftwareScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Cleaning ähnelt.
        /// </summary>
        public static string StartClearing {
            get {
                return ResourceManager.GetString("StartClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startup Entries ähnelt.
        /// </summary>
        public static string StartupScanTitle {
            get {
                return ResourceManager.GetString("StartupScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die successful. ähnelt.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Restore ähnelt.
        /// </summary>
        public static string SystemRestore {
            get {
                return ResourceManager.GetString("SystemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Restore deemed unavailable or deactivated. Option disabled. ähnelt.
        /// </summary>
        public static string SystemRestoreDeactivated {
            get {
                return ResourceManager.GetString("SystemRestoreDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Restore is either disabled or unavailable on this computer.  ähnelt.
        /// </summary>
        public static string SystemRestoreUnavailable {
            get {
                return ResourceManager.GetString("SystemRestoreUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Restore is turned off, Would you like to continue at your own risk? ähnelt.
        /// </summary>
        public static string SystemRestoreUnavailableRunFixAnyway {
            get {
                return ResourceManager.GetString("SystemRestoreUnavailableRunFixAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation Strings ähnelt.
        /// </summary>
        public static string UninstallScanTitle {
            get {
                return ResourceManager.GetString("UninstallScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Scan ähnelt.
        /// </summary>
        public static string UserScanTitle {
            get {
                return ResourceManager.GetString("UserScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Virtual Devices ähnelt.
        /// </summary>
        public static string VdmScanTitle {
            get {
                return ResourceManager.GetString("VdmScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to create a System Restore Point before proceeding? The Restore process may take several minutes to complete. ähnelt.
        /// </summary>
        public static string WouldYouLikeToCreateRestorePoint {
            get {
                return ResourceManager.GetString("WouldYouLikeToCreateRestorePoint", resourceCulture);
            }
        }
    }
}
