//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreemiumUtilities.RegCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreemiumUtilities.RegCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted deletion of value:.
        /// </summary>
        public static string AttemptedDeletionOfValue {
            get {
                return ResourceManager.GetString("AttemptedDeletionOfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Scan.
        /// </summary>
        public static string CancelScan {
            get {
                return ResourceManager.GetString("CancelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Scan.
        /// </summary>
        public static string ControlScanTitle {
            get {
                return ResourceManager.GetString("ControlScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Restore Point ....
        /// </summary>
        public static string CreatingRestorePoint {
            get {
                return ResourceManager.GetString("CreatingRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep System Scan.
        /// </summary>
        public static string DeepScanTitle {
            get {
                return ResourceManager.GetString("DeepScanTitle", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap desktop_icon {
            get {
                object obj = ResourceManager.GetObject("desktop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fonts.
        /// </summary>
        public static string FontScanTitle {
            get {
                return ResourceManager.GetString("FontScanTitle", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap frame0 {
            get {
                object obj = ResourceManager.GetObject("frame0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frame1 {
            get {
                object obj = ResourceManager.GetObject("frame1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frame2 {
            get {
                object obj = ResourceManager.GetObject("frame2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frame3 {
            get {
                object obj = ResourceManager.GetObject("frame3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frame4 {
            get {
                object obj = ResourceManager.GetObject("frame4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frame5 {
            get {
                object obj = ResourceManager.GetObject("frame5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frame6 {
            get {
                object obj = ResourceManager.GetObject("frame6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frame7 {
            get {
                object obj = ResourceManager.GetObject("frame7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Help Files.
        /// </summary>
        public static string HelpScanTitle {
            get {
                return ResourceManager.GetString("HelpScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History and Start Menu.
        /// </summary>
        public static string HistoryScanTitle {
            get {
                return ResourceManager.GetString("HistoryScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection!.
        /// </summary>
        public static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items cleared.
        /// </summary>
        public static string ItemsCleared {
            get {
                return ResourceManager.GetString("ItemsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last time you cleaned registry was {0:hh:mm dd-MM-yy}.
        /// </summary>
        public static string LastCleanTime {
            get {
                return ResourceManager.GetString("LastCleanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Libraries.
        /// </summary>
        public static string LibraryScanTitle {
            get {
                return ResourceManager.GetString("LibraryScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRU Lists.
        /// </summary>
        public static string MRUScanTitle {
            get {
                return ResourceManager.GetString("MRUScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Selected.
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check registry categories and press scan.
        /// </summary>
        public static string NotStartedHeader {
            get {
                return ResourceManager.GetString("NotStartedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string NowScanning {
            get {
                return ResourceManager.GetString("NowScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problems were found. To scan again is recommended to find more problems..
        /// </summary>
        public static string ProblemsFound {
            get {
                return ResourceManager.GetString("ProblemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problems were found. Select ones you want to remove and press Start Clearing..
        /// </summary>
        public static string ProblemsFoundClickClear {
            get {
                return ResourceManager.GetString("ProblemsFoundClickClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Cleaner.
        /// </summary>
        public static string RegistryCleaner {
            get {
                return ResourceManager.GetString("RegistryCleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Cleaning Completed.
        /// </summary>
        public static string RegistryCleaningCompleted {
            get {
                return ResourceManager.GetString("RegistryCleaningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Scan Canceled.
        /// </summary>
        public static string RegistryScanCanceled {
            get {
                return ResourceManager.GetString("RegistryScanCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Scan Completed.
        /// </summary>
        public static string RegistryScanCompleted {
            get {
                return ResourceManager.GetString("RegistryScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items removal action completed successfully..
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Disabled!.
        /// </summary>
        public static string RestoreDisabled {
            get {
                return ResourceManager.GetString("RestoreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Aborted, No Segments selected..
        /// </summary>
        public static string ScanAborted {
            get {
                return ResourceManager.GetString("ScanAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Aborted by User..
        /// </summary>
        public static string ScanAbortedByUser {
            get {
                return ResourceManager.GetString("ScanAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Again.
        /// </summary>
        public static string ScanAgain {
            get {
                return ResourceManager.GetString("ScanAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning:.
        /// </summary>
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Registry.
        /// </summary>
        public static string ScanningRegistry {
            get {
                return ResourceManager.GetString("ScanningRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Now.
        /// </summary>
        public static string ScanNow {
            get {
                return ResourceManager.GetString("ScanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Results were Reset..
        /// </summary>
        public static string ScanResultsReset {
            get {
                return ResourceManager.GetString("ScanResultsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Started....
        /// </summary>
        public static string ScanStarted {
            get {
                return ResourceManager.GetString("ScanStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any scan segments selected, please check at least one.
        /// </summary>
        public static string SelectAtLeastOneItem {
            get {
                return ResourceManager.GetString("SelectAtLeastOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any items for removal. To Reset the Scan Results, select Cancel.
        /// </summary>
        public static string SelectItemsToRemove {
            get {
                return ResourceManager.GetString("SelectItemsToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to set up System Restore before proceeding? Without System Restore, changes to your system can Not be Undone.
        /// </summary>
        public static string SetUpSystemRestore {
            get {
                return ResourceManager.GetString("SetUpSystemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Software.
        /// </summary>
        public static string SoftwareScanTitle {
            get {
                return ResourceManager.GetString("SoftwareScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cleaning.
        /// </summary>
        public static string StartClearing {
            get {
                return ResourceManager.GetString("StartClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Entries.
        /// </summary>
        public static string StartupScanTitle {
            get {
                return ResourceManager.GetString("StartupScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful..
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore.
        /// </summary>
        public static string SystemRestore {
            get {
                return ResourceManager.GetString("SystemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore deemed unavailable or deactivated. Option disabled..
        /// </summary>
        public static string SystemRestoreDeactivated {
            get {
                return ResourceManager.GetString("SystemRestoreDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore is either disabled or unavailable on this computer. .
        /// </summary>
        public static string SystemRestoreUnavailable {
            get {
                return ResourceManager.GetString("SystemRestoreUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore is turned off, Would you like to continue at your own risk?.
        /// </summary>
        public static string SystemRestoreUnavailableRunFixAnyway {
            get {
                return ResourceManager.GetString("SystemRestoreUnavailableRunFixAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Strings.
        /// </summary>
        public static string UninstallScanTitle {
            get {
                return ResourceManager.GetString("UninstallScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Scan.
        /// </summary>
        public static string UserScanTitle {
            get {
                return ResourceManager.GetString("UserScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Devices.
        /// </summary>
        public static string VdmScanTitle {
            get {
                return ResourceManager.GetString("VdmScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to create a System Restore Point before proceeding? The Restore process may take several minutes to complete..
        /// </summary>
        public static string WouldYouLikeToCreateRestorePoint {
            get {
                return ResourceManager.GetString("WouldYouLikeToCreateRestorePoint", resourceCulture);
            }
        }
    }
}
