//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugReporter.FreemiumWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FreemiumWebService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/SubmitNormalReport", ReplyAction="http://tempuri.org/IReportService/SubmitNormalReportResponse")]
        void SubmitNormalReport(string version, string action, string mac, string ipv6, string os, string hostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/SubmitBugReport", ReplyAction="http://tempuri.org/IReportService/SubmitBugReportResponse")]
        void SubmitBugReport(string version, string mac, string ipv6, string os, string hostName, string bugStackTrace, string bugType, string bugMessage, string bugUserInput, string bugTargetSite, string bugSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetLatestVersion", ReplyAction="http://tempuri.org/IReportService/GetLatestVersionResponse")]
        string[] GetLatestVersion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : BugReporter.FreemiumWebService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<BugReporter.FreemiumWebService.IReportService>, BugReporter.FreemiumWebService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitNormalReport(string version, string action, string mac, string ipv6, string os, string hostName) {
            base.Channel.SubmitNormalReport(version, action, mac, ipv6, os, hostName);
        }
        
        public void SubmitBugReport(string version, string mac, string ipv6, string os, string hostName, string bugStackTrace, string bugType, string bugMessage, string bugUserInput, string bugTargetSite, string bugSource) {
            base.Channel.SubmitBugReport(version, mac, ipv6, os, hostName, bugStackTrace, bugType, bugMessage, bugUserInput, bugTargetSite, bugSource);
        }
        
        public string[] GetLatestVersion() {
            return base.Channel.GetLatestVersion();
        }
    }
}
