//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrowserAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About URL.
        /// </summary>
        public static string AboutURL {
            get {
                return ResourceManager.GetString("AboutURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap bottomBar {
            get {
                object obj = ResourceManager.GetObject("bottomBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage browsers.
        /// </summary>
        public static string BrowserAssistant {
            get {
                return ResourceManager.GetString("BrowserAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome Extensions.
        /// </summary>
        public static string ChromeExtensions {
            get {
                return ResourceManager.GetString("ChromeExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to close {0} to view it&apos;s extensions. Please close {0}, before clicking on its tab again..
        /// </summary>
        public static string CloseBrowserError {
            get {
                return ResourceManager.GetString("CloseBrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Setting.
        /// </summary>
        public static string CurrentSetting {
            get {
                return ResourceManager.GetString("CurrentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Search.
        /// </summary>
        public static string CustomizeSearch {
            get {
                return ResourceManager.GetString("CustomizeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Page URL.
        /// </summary>
        public static string DefaultPageURL {
            get {
                return ResourceManager.GetString("DefaultPageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Search URL.
        /// </summary>
        public static string DefaultSearchURL {
            get {
                return ResourceManager.GetString("DefaultSearchURL", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap desktop_icon {
            get {
                object obj = ResourceManager.GetObject("desktop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Navigation.
        /// </summary>
        public static string DesktopNavigation {
            get {
                return ResourceManager.GetString("DesktopNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox Extensions.
        /// </summary>
        public static string FirefoxExtentions {
            get {
                return ResourceManager.GetString("FirefoxExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start firefox at least once, before using this feature..
        /// </summary>
        public static string FirstStart {
            get {
                return ResourceManager.GetString("FirstStart", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap help_off {
            get {
                object obj = ResourceManager.GetObject("help_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap help_on {
            get {
                object obj = ResourceManager.GetObject("help_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/company/faq/.
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijack Restore.
        /// </summary>
        public static string HijackRestore {
            get {
                return ResourceManager.GetString("HijackRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap icon_browser_manager {
            get {
                object obj = ResourceManager.GetObject("icon_browser_manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InPrivate.
        /// </summary>
        public static string InPrivate {
            get {
                return ResourceManager.GetString("InPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE ActiveX.
        /// </summary>
        public static string InternetExplorerActiveX {
            get {
                return ResourceManager.GetString("InternetExplorerActiveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE BHOs.
        /// </summary>
        public static string InternetExplorerBHOs {
            get {
                return ResourceManager.GetString("InternetExplorerBHOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE Extensions.
        /// </summary>
        public static string InternetExplorerExtensions {
            get {
                return ResourceManager.GetString("InternetExplorerExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE Toolbars.
        /// </summary>
        public static string InternetExplorerToolbars {
            get {
                return ResourceManager.GetString("InternetExplorerToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Page.
        /// </summary>
        public static string LocalPage {
            get {
                return ResourceManager.GetString("LocalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Canceled.
        /// </summary>
        public static string NavigationCanceled {
            get {
                return ResourceManager.GetString("NavigationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Failure.
        /// </summary>
        public static string NavigationFailure {
            get {
                return ResourceManager.GetString("NavigationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Add-ons.
        /// </summary>
        public static string NoAddons {
            get {
                return ResourceManager.GetString("NoAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Add-ons Info.
        /// </summary>
        public static string NoAddonsInfo {
            get {
                return ResourceManager.GetString("NoAddonsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not installed!.
        /// </summary>
        public static string NotInstalledError {
            get {
                return ResourceManager.GetString("NotInstalledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Information.
        /// </summary>
        public static string OfflineInformation {
            get {
                return ResourceManager.GetString("OfflineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post not Cached.
        /// </summary>
        public static string PostNotCached {
            get {
                return ResourceManager.GetString("PostNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Setting To.
        /// </summary>
        public static string RestoreSettingTo {
            get {
                return ResourceManager.GetString("RestoreSettingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Extensions.
        /// </summary>
        public static string SaveExtensions {
            get {
                return ResourceManager.GetString("SaveExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save IE ActiveX.
        /// </summary>
        public static string SaveIeActiveX {
            get {
                return ResourceManager.GetString("SaveIeActiveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save IE BHOs.
        /// </summary>
        public static string SaveIeBHOs {
            get {
                return ResourceManager.GetString("SaveIeBHOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save IE Extensions.
        /// </summary>
        public static string SaveIeExtensions {
            get {
                return ResourceManager.GetString("SaveIeExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save IE Toolbars.
        /// </summary>
        public static string SaveIeToolbars {
            get {
                return ResourceManager.GetString("SaveIeToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Assistant.
        /// </summary>
        public static string SearchAssistant {
            get {
                return ResourceManager.GetString("SearchAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchBar.
        /// </summary>
        public static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Page.
        /// </summary>
        public static string SearchPage {
            get {
                return ResourceManager.GetString("SearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Provider.
        /// </summary>
        public static string SearchProvider {
            get {
                return ResourceManager.GetString("SearchProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search URL.
        /// </summary>
        public static string SearchURL {
            get {
                return ResourceManager.GetString("SearchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Risk.
        /// </summary>
        public static string SecurityRisk {
            get {
                return ResourceManager.GetString("SecurityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Name.
        /// </summary>
        public static string SettingName {
            get {
                return ResourceManager.GetString("SettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap thinBar {
            get {
                object obj = ResourceManager.GetObject("thinBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Browser Manager!
        ///Choose the tab that corresponds to the browser configuration you want to change..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
