//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileEraser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileEraser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string abort_it {
            get {
                return ResourceManager.GetString("abort_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to delete.
        /// </summary>
        internal static string attempting {
            get {
                return ResourceManager.GetString("attempting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Shredding file(s).
        /// </summary>
        internal static string begin_shredding {
            get {
                return ResourceManager.GetString("begin_shredding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Running Instances.
        /// </summary>
        internal static string close_running_instances {
            get {
                return ResourceManager.GetString("close_running_instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your Administrator.
        /// </summary>
        internal static string contact_admin {
            get {
                return ResourceManager.GetString("contact_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete.
        /// </summary>
        internal static string could_not_delete {
            get {
                return ResourceManager.GetString("could_not_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        internal static string delete_file {
            get {
                return ResourceManager.GetString("delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Files in Directory.
        /// </summary>
        internal static string delete_files_directory {
            get {
                return ResourceManager.GetString("delete_files_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files in parent folder and all subfolders.
        /// </summary>
        internal static string delete_files_parent {
            get {
                return ResourceManager.GetString("delete_files_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string deleted {
            get {
                return ResourceManager.GetString("deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Multiple Files.
        /// </summary>
        internal static string deleting_files {
            get {
                return ResourceManager.GetString("deleting_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of.
        /// </summary>
        internal static string deletion_of {
            get {
                return ResourceManager.GetString("deletion_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Options.
        /// </summary>
        internal static string deletion_options {
            get {
                return ResourceManager.GetString("deletion_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory deletion(s) completed Successfully.
        /// </summary>
        internal static string dir_deleted {
            get {
                return ResourceManager.GetString("dir_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Destroyed.
        /// </summary>
        internal static string dir_destroyed {
            get {
                return ResourceManager.GetString("dir_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folders, too.
        /// </summary>
        internal static string eliminate_folders {
            get {
                return ResourceManager.GetString("eliminate_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emptying file contents failed.
        /// </summary>
        internal static string emptying_content_failed {
            get {
                return ResourceManager.GetString("emptying_content_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the file name or directory here.
        /// </summary>
        internal static string enter_file_name {
            get {
                return ResourceManager.GetString("enter_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file write failed verification test.
        /// </summary>
        internal static string failed_verification {
            get {
                return ResourceManager.GetString("failed_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deletion(s) completed Successfully.
        /// </summary>
        internal static string file_deleted {
            get {
                return ResourceManager.GetString("file_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Destroyed.
        /// </summary>
        internal static string file_destroyed {
            get {
                return ResourceManager.GetString("file_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be renamed.
        /// </summary>
        internal static string file_not_renamed {
            get {
                return ResourceManager.GetString("file_not_renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path is invalid.
        /// </summary>
        internal static string file_path_invalid {
            get {
                return ResourceManager.GetString("file_path_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Selection.
        /// </summary>
        internal static string file_selection {
            get {
                return ResourceManager.GetString("file_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) shredded successfully.
        /// </summary>
        internal static string file_shredded {
            get {
                return ResourceManager.GetString("file_shredded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase files securely.
        /// </summary>
        internal static string file_shredder {
            get {
                return ResourceManager.GetString("file_shredder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/company/faq/.
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path.
        /// </summary>
        internal static string invalid_path {
            get {
                return ResourceManager.GetString("invalid_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient access privileges to run this program. You must be logged on as the system administrator.
        /// </summary>
        internal static string no_sufficient_access {
            get {
                return ResourceManager.GetString("no_sufficient_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the file select or open folder dialog.
        /// </summary>
        internal static string open_file_select {
            get {
                return ResourceManager.GetString("open_file_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System Not Supported.
        /// </summary>
        internal static string os_not_supported {
            get {
                return ResourceManager.GetString("os_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse SubFolders.
        /// </summary>
        internal static string parse_subfolders {
            get {
                return ResourceManager.GetString("parse_subfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNM Enabled.
        /// </summary>
        internal static string pnm_enabled {
            get {
                return ResourceManager.GetString("pnm_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared to process.
        /// </summary>
        internal static string prepared_process {
            get {
                return ResourceManager.GetString("prepared_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared to shred.
        /// </summary>
        internal static string prepared_shred {
            get {
                return ResourceManager.GetString("prepared_shred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed.
        /// </summary>
        internal static string proceed {
            get {
                return ResourceManager.GetString("proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file.
        /// </summary>
        internal static string processing_file {
            get {
                return ResourceManager.GetString("processing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string scanning {
            get {
                return ResourceManager.GetString("scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File.
        /// </summary>
        internal static string select_file {
            get {
                return ResourceManager.GetString("select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a file or folder.
        /// </summary>
        internal static string select_file_folder {
            get {
                return ResourceManager.GetString("select_file_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder.
        /// </summary>
        internal static string select_folder {
            get {
                return ResourceManager.GetString("select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shred It.
        /// </summary>
        internal static string shred_it {
            get {
                return ResourceManager.GetString("shred_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! You are attempting to shred the drive! Operation Aborted!.
        /// </summary>
        internal static string shredding_drive {
            get {
                return ResourceManager.GetString("shredding_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some directories were not deleted.
        /// </summary>
        internal static string some_dir_not_deleted {
            get {
                return ResourceManager.GetString("some_dir_not_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files were not deleted.
        /// </summary>
        internal static string some_files_not_deleted {
            get {
                return ResourceManager.GetString("some_files_not_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Operating System is not supported. This application can be run on any NT based system (XP.Vista/2000/2003).
        /// </summary>
        internal static string system_not_supported {
            get {
                return ResourceManager.GetString("system_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate any running instance of the file pre-execution of the shredder.
        /// </summary>
        internal static string terminate_running {
            get {
                return ResourceManager.GetString("terminate_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option if you want to shred a single file.
        /// </summary>
        internal static string use_shred_file {
            get {
                return ResourceManager.GetString("use_shred_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option if you want to shred multiple files in a folder.
        /// </summary>
        internal static string use_shred_files {
            get {
                return ResourceManager.GetString("use_shred_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Us.
        /// </summary>
        internal static string visit_us {
            get {
                return ResourceManager.GetString("visit_us", resourceCulture);
            }
        }
    }
}
