//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartupManager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need admin rights to run..
        /// </summary>
        public static string AdminRightsNeeded {
            get {
                return ResourceManager.GetString("AdminRightsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string arguments {
            get {
                return ResourceManager.GetString("arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string command {
            get {
                return ResourceManager.GetString("command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All commands except delete are disabled.
        /// </summary>
        public static string commands_disabled {
            get {
                return ResourceManager.GetString("commands_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to delete the selected item.
        /// </summary>
        public static string delete_selected_item {
            get {
                return ResourceManager.GetString("delete_selected_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete startup item.
        /// </summary>
        public static string delete_startup_item {
            get {
                return ResourceManager.GetString("delete_startup_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable startup item.
        /// </summary>
        public static string disable_startup_item {
            get {
                return ResourceManager.GetString("disable_startup_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to continue.
        /// </summary>
        public static string do_you_wish {
            get {
                return ResourceManager.GetString("do_you_wish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable startup item.
        /// </summary>
        public static string enable_startup_item {
            get {
                return ResourceManager.GetString("enable_startup_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in.
        /// </summary>
        public static string error_occurred {
            get {
                return ResourceManager.GetString("error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute command.
        /// </summary>
        public static string execute_command {
            get {
                return ResourceManager.GetString("execute_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not appear to be a valid shortcut.
        /// </summary>
        public static string file_appear_not_valid {
            get {
                return ResourceManager.GetString("file_appear_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file and/or folder cannot be found.
        /// </summary>
        public static string file_folder_not_found {
            get {
                return ResourceManager.GetString("file_folder_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is invalid or does not exist.
        /// </summary>
        public static string file_invalid {
            get {
                return ResourceManager.GetString("file_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not found or is hidden.
        /// </summary>
        public static string file_not_found {
            get {
                return ResourceManager.GetString("file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not found.
        /// </summary>
        public static string file_not_found_warning {
            get {
                return ResourceManager.GetString("file_not_found_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not found.
        /// </summary>
        public static string file_not_found1 {
            get {
                return ResourceManager.GetString("file_not_found1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string file_path {
            get {
                return ResourceManager.GetString("file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder was not found.
        /// </summary>
        public static string folder_not_found {
            get {
                return ResourceManager.GetString("folder_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File version.
        /// </summary>
        public static string full_version {
            get {
                return ResourceManager.GetString("full_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/company/faq/.
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry: Current User.
        /// </summary>
        public static string HKCU {
            get {
                return ResourceManager.GetString("HKCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry: All Users.
        /// </summary>
        public static string HKLM {
            get {
                return ResourceManager.GetString("HKLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue, you will only be able to change those items marked &quot;Current user&quot;.
        /// </summary>
        public static string if_you_continue {
            get {
                return ResourceManager.GetString("if_you_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        public static string item_name {
            get {
                return ResourceManager.GetString("item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to All.
        /// </summary>
        public static string move_to_all {
            get {
                return ResourceManager.GetString("move_to_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move item to All users.
        /// </summary>
        public static string move_to_all_tip {
            get {
                return ResourceManager.GetString("move_to_all_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to &amp;All users.
        /// </summary>
        public static string move_to_all_users {
            get {
                return ResourceManager.GetString("move_to_all_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Current &amp;user.
        /// </summary>
        public static string move_to_current_user {
            get {
                return ResourceManager.GetString("move_to_current_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to User.
        /// </summary>
        public static string move_to_uesr {
            get {
                return ResourceManager.GetString("move_to_uesr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Item to Current user.
        /// </summary>
        public static string move_to_user_tip {
            get {
                return ResourceManager.GetString("move_to_user_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view the properties of this file.
        /// </summary>
        public static string no_permission {
            get {
                return ResourceManager.GetString("no_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file folder.
        /// </summary>
        public static string open_file_folder {
            get {
                return ResourceManager.GetString("open_file_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string open_folder {
            get {
                return ResourceManager.GetString("open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder containing startup item.
        /// </summary>
        public static string open_folder_tip {
            get {
                return ResourceManager.GetString("open_folder_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh display.
        /// </summary>
        public static string refresh_tip {
            get {
                return ResourceManager.GetString("refresh_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to change all startup items you must run this program as an administrator.
        /// </summary>
        public static string run_as_admin {
            get {
                return ResourceManager.GetString("run_as_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage startup.
        /// </summary>
        public static string startup_manager {
            get {
                return ResourceManager.GetString("startup_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Folder: All Users.
        /// </summary>
        public static string StartupAllUsers {
            get {
                return ResourceManager.GetString("StartupAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Folder: Current User.
        /// </summary>
        public static string StartupCurrentUser {
            get {
                return ResourceManager.GetString("StartupCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system returned the following information.
        /// </summary>
        public static string system_returned {
            get {
                return ResourceManager.GetString("system_returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this item.
        /// </summary>
        public static string unable_to_delete {
            get {
                return ResourceManager.GetString("unable_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to disable this item.
        /// </summary>
        public static string unable_to_disable {
            get {
                return ResourceManager.GetString("unable_to_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to enable this item.
        /// </summary>
        public static string unable_to_enable {
            get {
                return ResourceManager.GetString("unable_to_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute this item.
        /// </summary>
        public static string unable_to_execute {
            get {
                return ResourceManager.GetString("unable_to_execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move this item.
        /// </summary>
        public static string unable_to_move {
            get {
                return ResourceManager.GetString("unable_to_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the folder containing this item.
        /// </summary>
        public static string unable_to_open {
            get {
                return ResourceManager.GetString("unable_to_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Do not delete startup items unless you are 100% sure of what you are doing. In most cases, it is recommended that you use the &quot;Disable&quot; option instead..
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry: x86 Current User.
        /// </summary>
        public static string WHKCU {
            get {
                return ResourceManager.GetString("WHKCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry: x86 All Users.
        /// </summary>
        public static string WHKLM {
            get {
                return ResourceManager.GetString("WHKLM", resourceCulture);
            }
        }
    }
}
